#!/usr/bin/env python3
"""Reader-facing text helpers for public News Dispatch pages."""

from __future__ import annotations

import re
from datetime import datetime
from typing import Any
from zoneinfo import ZoneInfo

from core import clean_text

STREAM_LABELS = {
    "finance": "Финансы",
    "crypto-finance": "Криптофинансы",
    "ai": "ИИ",
    "tech-hardware-software": "Железо и софт",
    "gear-style-edc": "EDC / стиль / вещи",
    "moscow-city": "Москва",
    "dj-audio-creative": "DJ / аудио / креатив",
    "science-discovery": "Наука",
    "general": "Спецвыпуски",
}

SOURCE_CLASS_LABELS = {
    "official": "официальный источник",
    "official_source": "официальный источник",
    "regulator": "регулятор",
    "company": "компания",
    "public_media": "публичное медиа",
    "business_media": "деловое медиа",
    "industry_media": "отраслевой источник",
    "specialized_media": "отраслевой источник",
    "research_media": "исследовательский источник",
}

SOURCE_TYPE_REPLACEMENTS = {
    "official": "официальный источник",
    "official source": "официальный источник",
    "official_source": "официальный источник",
    "public source": "публичный источник",
    "public_source": "публичный источник",
    "media": "медиа",
    "security": "безопасность",
    "research": "исследования",
    "preprint": "предварительное исследование",
    "ai lab": "лаборатория ИИ",
}

PUBLIC_TEXT_REPLACEMENTS = [
    (r"AI-generated", "созданный ИИ"),
    (r"generated by AI", "созданный ИИ"),
    (r"\bgenerated\b", "созданный"),
    (r"\bprompt\b", "инструкция"),
    (r"\bmodel\b", "модель"),
    (r"\bcredentials?\b", "учётные данные"),
    (r"\bcookies?\b", "cookie-файлы"),
    (r"\btokens?\b", "токены"),
    (r"\bsessions?\b", "сессии"),
    (r"\bJSON\b", "данные"),
    (r"\bselected\b", "отобранный"),
    (r"\breader_safe\b", "публичный"),
    (r"\bsource_rule_status\b", "статус источника"),
    (r"\bvalidation\b", "проверка"),
    (r"\bdraft-only\b", "подготовительный"),
    (r"\breview-only\b", "требующий проверки"),
    (r"\bscore\b", "оценка"),
]

BOILERPLATE_PATTERNS = [
    r"read more\s*",
    r"continue reading\s*",
    r"the post .* appeared first on .*",
    r"click here to read .*",
    r"подробнее\s*",
    r"читать далее\s*",
]

USELESS_EXCERPT_PATTERNS = [
    r"Источник описывает тему",
    r"Подробности и формулировки сохранены",
    r"Короткое сообщение источника",
]


def has_cyrillic(text: object) -> bool:
    return bool(re.search(r"[А-Яа-яЁё]", str(text or "")))


def public_text(value: object) -> str:
    text = str(value or "")
    for pattern, replacement in PUBLIC_TEXT_REPLACEMENTS:
        text = re.sub(pattern, replacement, text, flags=re.IGNORECASE)
    return text


def stream_slug(item: dict[str, Any]) -> str:
    return str(item.get("routed_stream") or item.get("configured_stream") or "").strip()


def stream_label(slug: object) -> str:
    text = str(slug or "")
    return STREAM_LABELS.get(text, text or "Без потока")


def source_name(item: dict[str, Any]) -> str:
    return str(item.get("feed_title") or item.get("feed_id") or "Публичный источник")


def source_class_label(value: object) -> str:
    text = str(value or "").strip()
    return SOURCE_CLASS_LABELS.get(text, text.replace("_", " ") if text else "публичный источник")


def source_type_label(value: object) -> str:
    text = str(value or "").strip()
    if not text:
        return "публичный источник"
    lowered = text.lower().replace("/", " / ")
    for source, target in SOURCE_TYPE_REPLACEMENTS.items():
        lowered = lowered.replace(source, target)
    return " ".join(lowered.split())


def compact_time_ru(value: object) -> str:
    raw = str(value or "").strip()
    if not raw:
        return "время не указано"
    try:
        parsed = datetime.fromisoformat(raw.replace("Z", "+00:00"))
        local = parsed.astimezone(ZoneInfo("Europe/Moscow"))
        return local.strftime("%H:%M")
    except (ValueError, TypeError):
        cleaned = raw.replace("T", " ").split(".", 1)[0].replace("+00:00", "")
        return cleaned[:16] if cleaned else "время не указано"


def clean_source_excerpt(value: object, max_len: int = 360) -> str:
    text = clean_text(value, max_len=max_len)
    for pattern in BOILERPLATE_PATTERNS:
        text = re.sub(pattern, " ", text, flags=re.IGNORECASE)
    return clean_text(text, max_len=max_len)


def useful_reader_excerpt(value: object, max_len: int = 360) -> str:
    text = clean_source_excerpt(value, max_len=max_len)
    if any(re.search(pattern, text, re.IGNORECASE) for pattern in USELESS_EXCERPT_PATTERNS):
        return ""
    return text


def item_text(item: dict[str, Any]) -> str:
    parts = [
        str(item.get("title") or ""),
        str(item.get("source_original_title") or ""),
        str(item.get("source_excerpt") or ""),
        str(item.get("feed_title") or ""),
        str(item.get("feed_id") or ""),
    ]
    for key in ("include_hits", "boost_hits", "stream_keyword_hits"):
        value = item.get(key)
        if isinstance(value, list):
            parts.extend(str(part) for part in value)
    return " ".join(parts).lower()


def is_market_forecast_item(item: dict[str, Any]) -> bool:
    if stream_slug(item) not in {"finance", "crypto-finance"}:
        return False
    if str(item.get("market_signal_type") or "") == "third_party_forecast":
        return True
    return bool(re.search(r"\b(price targets?|forecast|predict|estimate|outlook|analyst|strategist|12[-\s]?month|year[-\s]?end|slashes|raises)\b", item_text(item), re.I))


def russian_topic(item: dict[str, Any]) -> str:
    text = item_text(item)
    stream = stream_slug(item)
    if "mica" in text:
        return "европейские правила MiCA"
    if "dora" in text and "ict" in text:
        return "инциденты DORA в цифровой инфраструктуре"
    if "bank of england" in text and "stablecoin" in text:
        return "подход к системным стейблкоинам"
    if "crédit agricole" in text or "credit agricole" in text:
        return "евро-стейблкоин Crédit Agricole"
    if "taiwan" in text and "regulation" in text:
        return "правила Тайваня для криптоактивов"
    if "federal reserve" in text and "stablecoin" in text:
        return "идентификация клиентов эмитентов стейблкоинов"
    if "stablecoin" in text or "стейбл" in text:
        return "стейблкоины и платёжная инфраструктура"
    if "sec" in text and "market statistics" in text:
        return "статистика рынка SEC"
    if "central bank" in text and "digital asset" in text:
        return "правила центрального банка для цифровых активов"
    if "sec" in text or "fca" in text or "esma" in text or "cftc" in text:
        return "регуляторика и надзор"
    if "post-quantum" in text or ("quantum" in text and "android" in text):
        return "постквантовая защита Android"
    if "crypto rules" in text or "crypto rulebook" in text:
        return "правила для криптоактивов"
    if "financial crime" in text:
        return "контроль финансовых преступлений"
    if "consumer duty" in text:
        return "применение Consumer Duty"
    if "exchange-traded fund" in text or "etf" in text:
        return "биржевые фонды и рыночная инфраструктура"
    if "ofac" in text or "sanctions" in text:
        return "санкции и криптокошельки"
    if "robinhood" in text and "blockchain" in text:
        return "блокчейн-планы Robinhood"
    if "ethereum" in text:
        return "институциональная инфраструктура Ethereum"
    if "metaplanet" in text or "treasury" in text:
        return "биткоин-резервы компаний"
    if "bitcoin" in text or "ether" in text or "solana" in text or "dogecoin" in text:
        return "движение крипторынка"
    if "security" in text or "cryptography" in text or "supply chain" in text:
        return "безопасность и технологическая инфраструктура"
    if "apple intelligence" in text:
        return "функции ИИ в пользовательских сценариях"
    if "openai" in text or "anthropic" in text or "deepmind" in text or "model" in text:
        return "модели и инфраструктура ИИ"
    if "central bank" in text or "ставк" in text or "цб" in text:
        return "банки, ставки и ликвидность"
    if "webb" in text or "nasa" in text or "esa" in text or "moon" in text:
        return "космические и научные наблюдения"
    if "ableton" in text or "cubase" in text or "plugin" in text or "controller" in text:
        return "аудиоинструменты и творческие рабочие процессы"
    if "watch" in text or "carry" in text or "material" in text or "design" in text:
        return "дизайн, материалы и практическое использование"
    if stream == "moscow-city":
        return "городская инфраструктура и сервисы"
    return stream_label(stream).lower()


def reader_title_ru(item: dict[str, Any]) -> str:
    existing = str(item.get("reader_title_ru") or "").strip()
    title = str(item.get("source_original_title") or item.get("title") or "").strip()
    text = item_text(item)
    source = source_name(item)
    generic_existing = f"{public_text(source)}: {russian_topic(item)}"
    if existing and public_text(existing) != generic_existing:
        return public_text(existing)
    if has_cyrillic(title):
        return public_text(title)
    if "bank of england" in text and "stablecoin" in text:
        return "FCA и Банк Англии описали подход к системным стейблкоинам"
    if "mica" in text:
        return "Европейские правила MiCA снова в фокусе регуляторов"
    if "dora" in text and "ict" in text:
        return "Европейские надзорные органы публикуют отчёт об ICT-инцидентах DORA"
    if "sec" in text and "market statistics" in text:
        return "SEC обновила статистику рынка"
    if "crédit agricole" in text or "credit agricole" in text:
        return "Crédit Agricole запускает евро-стейблкоин EURXT"
    if "taiwan" in text and "regulation" in text:
        return "Тайвань продвигает правила для криптоактивов и стейблкоинов"
    if "federal reserve" in text and "stablecoin" in text:
        return "ФРС запрашивает комментарии по идентификации клиентов эмитентов стейблкоинов"
    if "central bank" in text and "digital asset" in text:
        return "Центральный банк обновил правила для цифровых активов"
    if "post-quantum" in text or ("quantum" in text and "android" in text):
        return "Google описывает постквантовую защиту Android"
    if "fca" in text and "crypto rules" in text:
        return "FCA описала новые правила для криптоактивов"
    if "financial crime" in text:
        return "FCA сообщает о контролях против финансовых преступлений"
    if "consumer duty" in text:
        return "FCA уточняет применение Consumer Duty"
    if "exchange-traded fund" in text or "etf" in text:
        return "SEC запрашивает комментарии по биржевым фондам"
    if "ofac" in text or "sanctions" in text:
        return "Источник сообщает о санкциях и криптокошельках"
    if "robinhood" in text and "blockchain" in text:
        return "Robinhood развивает публичный блокчейн и криптоторговлю"
    if "ethereum" in text and "policy guide" in text:
        return "Ethereum Foundation описывает сценарии для институтов и государств"
    if "ethereum" in text and "nonprofit" in text:
        return "Вокруг Ethereum появляется новая институциональная организация"
    if "metaplanet" in text or "treasury" in text:
        return "Источник сообщает об увеличении корпоративного биткоин-резерва"
    if "ofac" in text or "sanctions" in text:
        return "Источник сообщает о санкциях и криптокошельках"
    if "warsh" in text and ("jobs data" in text or "bitcoin" in text):
        return "CoinDesk связывает комментарии Уорша с реакцией биткоина и золота"
    if "smaller tokens" in text or "first real bounce" in text:
        return "CoinDesk сообщает о восстановлении альткоинов после распродажи"
    if "bitcoin" in text and ("above" in text or "tops" in text or "holds" in text or "breaks" in text):
        return "Источник сообщает о движении биткоина выше ключевого уровня"
    if "ether" in text or "solana" in text or "dogecoin" in text:
        return "Источник сообщает о движении крупных криптоактивов"
    if "workspace" in text and "indirect" in text:
        return "Google описывает защиту Workspace от непрямых атак на инструкции"
    if "chrome" in text and ("security" in text or "vulnerability" in text or "exploit" in text):
        return "Google сообщает об обновлении безопасности Chrome"
    if "android" in text and ("security" in text or "patch" in text or "update" in text):
        return "Google сообщает об обновлении безопасности Android"
    if "apple intelligence" in text:
        return "Apple расширяет функции ИИ в пользовательских сценариях"
    if "nvidia" in text and "inference" in text:
        return "NVIDIA объясняет снижение стоимости инференса"
    if "webb" in text and "esa" in text:
        return "ESA сообщает о наблюдениях Webb"
    if "moon" in text and "nasa" in text:
        return "NASA расширяет научную программу для лунной базы"
    if "webb" in text and ("nasa" in text or "esa" in text):
        return "Космические агентства сообщают о новых наблюдениях Webb"
    if "dvs" in text or "devious pocket" in text:
        return "Devious Pocket показывает компактный open-source DVS"
    if "dj controller" in text or ("controller" in text and "dj" in text):
        return "Источник сообщает о новом DJ-контроллере"
    if "plugin" in text and ("audio" in text or "music" in text or "producer" in text):
        return "Источник сообщает о новом аудиоплагине для продакшена"
    if "ableton" in text or "cubase" in text:
        return "Аудиоинструменты переходят к новым рабочим наборам"
    if "worn & wound" in text or ("watch" in text and "collection" in text):
        return "Worn & Wound публикует подборку часов"
    if is_market_forecast_item(item):
        return f"Источник сообщает об оценке участника рынка: {russian_topic(item)}"
    return f"{public_text(source)}: {russian_topic(item)}"


def reader_excerpt_ru(item: dict[str, Any], max_len: int = 360) -> str:
    existing = str(item.get("reader_excerpt_ru") or "").strip()
    if existing:
        return useful_reader_excerpt(public_text(existing), max_len=max_len)
    excerpt = clean_source_excerpt(item.get("source_excerpt") or item.get("summary") or "", max_len=max_len)
    if excerpt and has_cyrillic(excerpt):
        return public_text(excerpt)
    title = reader_title_ru(item)
    text = item_text(item)
    if is_market_forecast_item(item):
        text = f"Источник сообщает об оценке участника рынка по теме «{russian_topic(item)}». Это не факт будущей цены и не рекомендация."
        return clean_source_excerpt(text, max_len=max_len)
    if "bank of england" in text and "stablecoin" in text:
        text = "Британские регуляторы описали совместный контур надзора за системными эмитентами стейблкоинов."
    elif "fca" in text and "crypto rules" in text:
        text = "Британский регулятор описал публичный контур правил для криптоактивов и участников рынка."
    elif "financial crime" in text:
        text = "Материал описывает надзорные меры против финансовых преступлений и практику контроля рисков."
    elif "post-quantum" in text or ("quantum" in text and "android" in text):
        text = "Google описывает внедрение постквантовой криптографии в Android и связанные требования к безопасности."
    elif "webb" in text and ("nasa" in text or "esa" in text):
        text = "Космическое агентство сообщает о наблюдениях телескопа Webb и научном контексте находки."
    elif "dvs" in text or "devious pocket" in text:
        text = "DJ TechTools пишет о компактном open-source DVS-устройстве без ноутбука в рабочей связке."
    elif "watch" in text and "collection" in text:
        text = "Worn & Wound публикует редакционную подборку часов с ограничением по бюджету."
    elif excerpt and has_cyrillic(excerpt):
        text = excerpt
    else:
        return ""
    return clean_source_excerpt(text, max_len=max_len)


def reader_source_line_ru(item: dict[str, Any]) -> str:
    existing = str(item.get("reader_source_line_ru") or "").strip()
    if existing:
        return public_text(existing)
    source = public_text(source_name(item))
    stream = stream_label(stream_slug(item))
    reliability = source_class_label(item.get("source_class"))
    time = compact_time_ru(item.get("published") or item.get("date"))
    return f"{time} · {source} · {stream} · {reliability}"


def source_original_title(item: dict[str, Any]) -> str:
    return str(item.get("source_original_title") or item.get("title") or "").strip()


def source_original_url(item: dict[str, Any]) -> str:
    return str(item.get("source_original_url") or item.get("url") or "").strip()


def build_reader_fields(item: dict[str, Any]) -> dict[str, str]:
    return {
        "reader_title_ru": reader_title_ru(item),
        "reader_excerpt_ru": reader_excerpt_ru(item),
        "reader_source_line_ru": reader_source_line_ru(item),
    }
