#!/usr/bin/env python3
"""Reader-facing text helpers for public News Dispatch pages."""

from __future__ import annotations

import re
from datetime import datetime, time
from typing import Any
from zoneinfo import ZoneInfo

from core import clean_text

STREAM_LABELS = {
    "finance": "Финансы",
    "crypto-finance": "Криптофинансы",
    "ai": "ИИ",
    "tech-hardware-software": "Железо и софт",
    "gear-style-edc": "EDC / стиль / вещи",
    "moscow-city": "Москва",
    "dj-audio-creative": "DJ / аудио / креатив",
    "science-discovery": "Наука",
    "general": "Спецвыпуски",
}

PUBLIC_TZ = ZoneInfo("Europe/Moscow")
MONTHS_RU = {
    1: "января",
    2: "февраля",
    3: "марта",
    4: "апреля",
    5: "мая",
    6: "июня",
    7: "июля",
    8: "августа",
    9: "сентября",
    10: "октября",
    11: "ноября",
    12: "декабря",
}

SOURCE_CLASS_LABELS = {
    "official": "официальный источник",
    "official_source": "официальный источник",
    "regulator": "регулятор",
    "company": "компания",
    "public_media": "публичное медиа",
    "business_media": "деловое медиа",
    "industry_media": "отраслевой источник",
    "specialized_media": "отраслевой источник",
    "research_media": "исследовательский источник",
}

SOURCE_TYPE_REPLACEMENTS = {
    "official": "официальный источник",
    "official source": "официальный источник",
    "official_source": "официальный источник",
    "public source": "публичный источник",
    "public_source": "публичный источник",
    "media": "медиа",
    "security": "безопасность",
    "research": "исследования",
    "preprint": "предварительное исследование",
    "ai lab": "лаборатория ИИ",
}

PUBLIC_TEXT_REPLACEMENTS = [
    (r"AI-generated", "созданный ИИ"),
    (r"generated by AI", "созданный ИИ"),
    (r"\bgenerated\b", "созданный"),
    (r"\bprompt\b", "инструкция"),
    (r"\bcredentials?\b", "учётные данные"),
    (r"\bcookies?\b", "cookie-файлы"),
    (r"\bsessions?\b", "сессии"),
    (r"\bJSON\b", "данные"),
    (r"\bselected\b", "отобранный"),
    (r"\breader_safe\b", "публичный"),
    (r"\bsource_rule_status\b", "статус источника"),
    (r"\bvalidation\b", "проверка"),
    (r"\bcoverage\b", "reporting"),
    (r"\bthreshold\b", "limit"),
    (r"\bdraft-only\b", "подготовительный"),
    (r"\breview-only\b", "требующий проверки"),
    (r"\bscore\b", "оценка"),
]

BOILERPLATE_PATTERNS = [
    r"\bvideo:\s*\d{1,2}:\d{2}:\d{2}\s*",
    r"read more\s*",
    r"continue reading\s*",
    r"the post .* appeared first on .*",
    r"click here to read .*",
    r"подробнее\s*",
    r"читать далее\s*",
]

GENERIC_SOURCE_TOPICS = {
    "регуляторика и надзор",
    "банки ставки и ликвидность",
    "безопасность и технологическая инфраструктура",
    "модели и инфраструктура ии",
    "движение крипторынка",
}

GENERIC_READER_SUMMARY_PHRASES = (
    "опубликованы новые сведения по теме",
    "опубликован новый исследовательский результат по теме",
    "представлен новый продукт или обновление по теме",
    "опубликовано изменение правил или надзорного подхода по теме",
)

PUBLIC_STORY_STOPWORDS = {
    "about", "after", "again", "against", "and", "announced", "announces", "before", "city", "crypto", "discovery",
    "finance", "from", "hardware", "into", "item", "latest", "new", "news", "over", "published", "publishes",
    "report", "reports", "says", "science", "software", "story", "technology", "that", "the", "their", "this",
    "through", "update", "updated", "updates", "with",
    "апреля", "августа", "будет", "были", "было", "декабря", "для", "изменения", "изменили", "июля", "июня",
    "как", "марта", "мая", "метро", "москва", "москве", "московский", "на", "ноября",
    "новая", "новое", "новости", "новый", "обновил", "обновила", "обновление", "опубликовал", "опубликовала",
    "октября", "после", "при", "районе", "ремонт", "сентября", "сообщает", "сообщил", "сообщила", "станции",
    "стало", "столице", "улице", "февраля", "через", "чтобы", "этого", "января", "закроют",
}

WHY_IT_MATTERS_BY_STREAM = {
    "finance": (
        "Материал помогает отслеживать изменения денежно-кредитной политики, "
        "банковского регулирования и условий работы финансового рынка."
    ),
    "crypto-finance": (
        "Материал помогает отслеживать правила и инфраструктуру цифровых активов; "
        "практический эффект зависит от статуса документа и сроков применения."
    ),
    "ai": (
        "Материал помогает отслеживать возможности, ограничения и инфраструктуру ИИ; "
        "заявленные результаты требуют проверки по первоисточнику."
    ),
    "tech-hardware-software": (
        "Материал помогает оценить изменения платформ, безопасности и технологических зависимостей."
    ),
    "gear-style-edc": (
        "Материал помогает оценить практическую полезность, качество и изменения потребительских сценариев."
    ),
    "moscow-city": (
        "Материал помогает понять изменения городской среды, инфраструктуры и доступности сервисов."
    ),
    "dj-audio-creative": (
        "Материал помогает отслеживать инструменты, совместимость и условия творческой работы."
    ),
    "science-discovery": (
        "Материал помогает отслеживать новые результаты; границы применимости зависят от методики и независимой проверки."
    ),
}


def has_cyrillic(text: object) -> bool:
    return bool(re.search(r"[А-Яа-яЁё]", str(text or "")))


def public_text(value: object) -> str:
    text = str(value or "")
    for pattern, replacement in PUBLIC_TEXT_REPLACEMENTS:
        text = re.sub(pattern, replacement, text, flags=re.IGNORECASE)
    return text


def normalized_public_topic(text: object) -> str:
    raw = re.sub(r"\s+", " ", str(text or "")).strip().lower()
    return re.sub(r"[^0-9a-zа-яё]+", " ", raw).strip()


def has_market_regulator_token(text: str, token: str | None = None) -> bool:
    pattern = r"\b(sec|fca|esma|cftc)\b" if token is None else rf"\b{re.escape(token)}\b"
    return bool(re.search(pattern, text, flags=re.IGNORECASE))


def is_source_topic_title(title: object) -> bool:
    text = str(title or "")
    if ":" not in text:
        return False
    _source, topic = text.split(":", 1)
    return normalized_public_topic(topic) in GENERIC_SOURCE_TOPICS


def is_generic_reader_summary(value: object) -> bool:
    text = str(value or "").lower()
    return any(phrase in text for phrase in GENERIC_READER_SUMMARY_PHRASES)


def stream_slug(item: dict[str, Any]) -> str:
    return str(item.get("routed_stream") or item.get("configured_stream") or "").strip()


def stream_label(slug: object) -> str:
    text = str(slug or "")
    return STREAM_LABELS.get(text, text or "Без потока")


def source_name(item: dict[str, Any]) -> str:
    return str(item.get("feed_title") or item.get("feed_id") or "Публичный источник")


def source_class_label(value: object) -> str:
    text = str(value or "").strip()
    return SOURCE_CLASS_LABELS.get(text, text.replace("_", " ") if text else "публичный источник")


def source_type_label(value: object) -> str:
    text = str(value or "").strip()
    if not text:
        return "публичный источник"
    lowered = text.lower().replace("/", " / ")
    for source, target in SOURCE_TYPE_REPLACEMENTS.items():
        lowered = lowered.replace(source, target)
    return " ".join(lowered.split())


def compact_time_ru(value: object) -> str:
    raw = str(value or "").strip()
    if not raw:
        return "время не указано"
    try:
        parsed = datetime.fromisoformat(raw.replace("Z", "+00:00"))
        local = parsed.astimezone(ZoneInfo("Europe/Moscow"))
        return local.strftime("%H:%M")
    except (ValueError, TypeError):
        cleaned = raw.replace("T", " ").split(".", 1)[0].replace("+00:00", "")
        return cleaned[:16] if cleaned else "время не указано"


def parse_public_datetime(value: object) -> tuple[datetime | None, bool]:
    raw = str(value or "").strip()
    if not raw:
        return None, False
    has_time = bool(re.search(r"[T ]\d{1,2}:\d{2}", raw))
    cleaned = raw.replace("Z", "+00:00")
    try:
        parsed = datetime.fromisoformat(cleaned)
    except ValueError:
        date_match = re.match(r"^(\d{4})-(\d{2})-(\d{2})$", raw)
        if not date_match:
            return None, False
        year, month, day = (int(part) for part in date_match.groups())
        return datetime(year, month, day, tzinfo=PUBLIC_TZ), False
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=PUBLIC_TZ)
    else:
        parsed = parsed.astimezone(PUBLIC_TZ)
    return parsed, has_time


def format_public_time_ru(value: object) -> str:
    parsed, has_time = parse_public_datetime(value)
    if parsed is None:
        return "дата не указана"
    day = f"{parsed.day} {MONTHS_RU[parsed.month]}"
    if has_time and parsed.date() == datetime.now(PUBLIC_TZ).date():
        return f"Сегодня, {parsed:%H:%M}"
    if has_time and parsed.timetz().replace(tzinfo=None) != time(0, 0):
        return f"{day}, {parsed:%H:%M}"
    return day


def public_item_is_fresh(item: dict[str, Any], reference: object, max_age_hours: int) -> bool:
    published, _published_has_time = parse_public_datetime(item.get("published") or item.get("date"))
    reference_dt, reference_has_time = parse_public_datetime(reference)
    if published is None or reference_dt is None:
        return False
    if not reference_has_time:
        reference_dt = reference_dt.replace(hour=23, minute=59, second=59)
    age_hours = (reference_dt - published).total_seconds() / 3600
    return -6 <= age_hours <= max_age_hours


def clean_source_excerpt(value: object, max_len: int = 360) -> str:
    text = clean_text(value, max_len=0)
    for pattern in BOILERPLATE_PATTERNS:
        text = re.sub(pattern, " ", text, flags=re.IGNORECASE)
    text = clean_text(text, max_len=0)
    if max_len and len(text) > max_len:
        shortened = text[: max_len - 1].rstrip()
        if " " in shortened:
            shortened = shortened.rsplit(" ", 1)[0]
        return shortened.rstrip(" ,;:-") + "…"
    return text


def item_text(item: dict[str, Any]) -> str:
    parts = [
        str(item.get("title") or ""),
        str(item.get("source_original_title") or ""),
        str(item.get("source_excerpt") or ""),
        str(item.get("feed_title") or ""),
        str(item.get("feed_id") or ""),
    ]
    for key in ("include_hits", "boost_hits", "stream_keyword_hits"):
        value = item.get(key)
        if isinstance(value, list):
            parts.extend(str(part) for part in value)
    return " ".join(parts).lower()


def is_market_forecast_item(item: dict[str, Any]) -> bool:
    if stream_slug(item) not in {"finance", "crypto-finance"}:
        return False
    if str(item.get("market_signal_type") or "") == "third_party_forecast":
        return True
    return bool(re.search(r"\b(price targets?|forecast|predict|estimate|outlook|analyst|strategist|12[-\s]?month|year[-\s]?end|slashes|raises)\b", item_text(item), re.I))


def russian_topic(item: dict[str, Any]) -> str:
    text = item_text(item)
    stream = stream_slug(item)
    if "mica" in text:
        return "европейские правила MiCA"
    if "dora" in text and "ict" in text:
        return "инциденты DORA в цифровой инфраструктуре"
    if "bank of england" in text and "stablecoin" in text:
        return "подход к системным стейблкоинам"
    if "crédit agricole" in text or "credit agricole" in text:
        return "евро-стейблкоин Crédit Agricole"
    if "taiwan" in text and "regulation" in text:
        return "правила Тайваня для криптоактивов"
    if "federal reserve" in text and "stablecoin" in text:
        return "идентификация клиентов эмитентов стейблкоинов"
    if "stablecoin" in text or "стейбл" in text:
        return "стейблкоины и платёжная инфраструктура"
    if has_market_regulator_token(text, "sec") and "market statistics" in text:
        return "статистика рынка SEC"
    if "central bank" in text and "digital asset" in text:
        return "правила центрального банка для цифровых активов"
    if has_market_regulator_token(text):
        return "регуляторика и надзор"
    if "post-quantum" in text or ("quantum" in text and "android" in text):
        return "постквантовая защита Android"
    if "crypto rules" in text or "crypto rulebook" in text:
        return "правила для криптоактивов"
    if "financial crime" in text:
        return "контроль финансовых преступлений"
    if "consumer duty" in text:
        return "применение Consumer Duty"
    if "exchange-traded fund" in text or "etf" in text:
        return "биржевые фонды и рыночная инфраструктура"
    if "ofac" in text or "sanctions" in text:
        return "санкции и криптокошельки"
    if "robinhood" in text and "blockchain" in text:
        return "блокчейн-планы Robinhood"
    if "ethereum" in text:
        return "институциональная инфраструктура Ethereum"
    if "metaplanet" in text or "treasury" in text:
        return "биткоин-резервы компаний"
    if "bitcoin" in text or "ether" in text or "solana" in text or "dogecoin" in text:
        return "движение крипторынка"
    if "security" in text or "cryptography" in text or "supply chain" in text:
        return "безопасность и технологическая инфраструктура"
    if "apple intelligence" in text:
        return "функции ИИ в пользовательских сценариях"
    if "openai" in text or "anthropic" in text or "deepmind" in text or "model" in text:
        return "модели и инфраструктура ИИ"
    if "central bank" in text or "ставк" in text or "цб" in text:
        return "банки, ставки и ликвидность"
    if "webb" in text or "nasa" in text or "esa" in text or "moon" in text:
        return "космические и научные наблюдения"
    if "ableton" in text or "cubase" in text or "plugin" in text or "controller" in text:
        return "аудиоинструменты и творческие рабочие процессы"
    if "watch" in text or "carry" in text or "material" in text or "design" in text:
        return "дизайн, материалы и практическое использование"
    if stream == "moscow-city":
        return "городская инфраструктура и сервисы"
    return stream_label(stream).lower()


def fallback_reader_title_base_ru(item: dict[str, Any]) -> str:
    source = public_text(source_name(item))
    templates = {
        "finance": f"{source} сообщает о событии на финансовом рынке",
        "crypto-finance": f"{source} сообщает о событии на рынке цифровых активов",
        "ai": f"{source} представил материал о развитии ИИ",
        "tech-hardware-software": f"{source} сообщает об изменениях в технологиях и безопасности",
        "gear-style-edc": f"{source} представил новый продукт и его практические особенности",
        "moscow-city": f"{source} сообщает об изменениях в городской жизни Москвы",
        "dj-audio-creative": f"{source} представил новый инструмент для работы со звуком",
        "science-discovery": f"{source} опубликовал новый научный результат",
    }
    return templates.get(stream_slug(item), f"{source} опубликовал новый материал")


def title_with_original_ru(base: str, original: str) -> str:
    raw = str(original or "").strip()
    cleaned = public_text(raw).strip()
    if cleaned and not has_cyrillic(raw):
        return f"{base}: {clean_source_excerpt(cleaned, max_len=110)}"
    return base


def fallback_reader_title_ru(item: dict[str, Any]) -> str:
    """Return a useful Russian heading when no event-specific template matches."""
    return title_with_original_ru(fallback_reader_title_base_ru(item), source_original_title(item))


def reader_title_ru(item: dict[str, Any]) -> str:
    existing = str(item.get("reader_title_ru") or "").strip()
    if existing:
        cleaned_existing = public_text(existing)
        generic_source_topic = f"{public_text(source_name(item))}: {russian_topic(item)}"
        generic_fallback = fallback_reader_title_base_ru(item)
        if (
            has_cyrillic(cleaned_existing)
            and not is_source_topic_title(cleaned_existing)
            and cleaned_existing != generic_source_topic
            and cleaned_existing != generic_fallback
        ):
            return cleaned_existing
    title = str(item.get("source_original_title") or item.get("title") or "").strip()
    if has_cyrillic(title):
        return public_text(title)
    text = item_text(item)
    source = source_name(item)
    original_product = title.split(":", 1)[0].strip() if ":" in title else ""
    if "galaxy" in text and "stablecoin yield" in text and "defi vault" in text:
        return "Galaxy запускает DeFi-хранилища для институциональной доходности в стейблкоинах"
    if "sec vs cftc" in text and "regulates crypto" in text:
        return "Как SEC и CFTC разделяют надзор за крипторынком"
    if "citadel securities" in text and "crypto.com" in text and "$400 million" in text:
        return "Citadel Securities инвестирует $400 млн в Crypto.com при оценке биржи в $20 млрд"
    if "federal reserve" in text and "enforcement action" in text and "heritage state bank" in text:
        return "ФРС применила надзорную меру к бывшему кредитному директору Heritage State Bank"
    if "7700x3d" in text and "exclusive to newegg" in text and "$329" in text:
        return "AMD Ryzen 7 7700X3D временно доступен только в Newegg за $329"
    if "fatf" in text and "aml enforcement" in text and "stablecoin crime" in text:
        return "FATF призывает ускорить применение AML-правил к крипторынку"
    if "bank of canada" in text and "monetary policy report" in text:
        return "Банк Канады опубликовал июльский доклад о денежно-кредитной политике"
    if "bank of canada" in text and "maintains the policy rate" in text:
        return "Банк Канады сохранил ключевую ставку на уровне 2,25%"
    if "sec" in text and "e-delivery" in text:
        return "SEC предложила новый порядок электронной доставки материалов инвесторам"
    if "bank of england" in text and "stablecoin" in text:
        return "FCA и Банк Англии описали подход к системным стейблкоинам"
    if "fca" in text and "systemic stablecoin" in text:
        return "FCA представила правила для системных стейблкоинов"
    if "mica" in text:
        return "Европейские правила MiCA снова в фокусе регуляторов"
    if "dora" in text and "ict" in text:
        return "Европейские надзорные органы публикуют отчёт об ICT-инцидентах DORA"
    if has_market_regulator_token(text, "sec") and "market statistics" in text:
        return "SEC обновила статистику рынка"
    if "crédit agricole" in text or "credit agricole" in text:
        return "Crédit Agricole запускает евро-стейблкоин EURXT"
    if "taiwan" in text and "regulation" in text:
        return "Тайвань продвигает правила для криптоактивов и стейблкоинов"
    if "federal reserve" in text and "stablecoin" in text:
        return "ФРС запрашивает комментарии по идентификации клиентов эмитентов стейблкоинов"
    if "central bank" in text and "digital asset" in text:
        return "Центральный банк обновил правила для цифровых активов"
    if "post-quantum" in text or ("quantum" in text and "android" in text):
        return "Google описывает постквантовую защиту Android"
    if "ace studio 2" in text and "review" in text:
        return "Обзор ACE Studio 2: функции ИИ сильнее рабочего процесса"
    if "rtx 3060" in text and "palit" in text:
        return "Palit возвращает GeForce RTX 3060 в версии Infinity 2 OC"
    if "perseverance" in text and "ancient mars impacts" in text:
        return "Perseverance нашёл на Марсе следы серии древних астероидных ударов"
    if "perseverance" in text and "broom point" in text:
        return "NASA показала маршрут Perseverance к древним породам Broom Point"
    if "young galaxy cluster" in text and ("webb" in text or "james webb" in text):
        return "Webb показал молодое скопление сливающихся галактик"
    if "digital euro" in text and "cooperative spirit" in text:
        return "ЕЦБ объяснил роль сотрудничества банков в развитии цифрового евро"
    if "teens deserve access to safe ai" in text:
        return "OpenAI объяснила, как делает доступ подростков к ИИ безопаснее"
    if "eu will force google" in text and "search data" in text and "android" in text:
        return "ЕС обяжет Google открыть поисковые данные и доступ к ИИ на Android"
    if "nanopore" in text and "current-induced heating" in text and "memory operations" in text:
        return "Нанопоровое устройство использует нагрев током для операций памяти"
    if "nodus" in text and "raven" in text and "trailtrekker" in text:
        return "Nodus и Raven представили четвёртую версию часов TrailTrekker"
    if "balyasny" in text and "ai research engine" in text:
        return "Balyasny построила исследовательскую систему на основе ИИ"
    if "near-earth asteroid" in text and "actually comet" in text:
        return "NASA выяснила, что околоземный астероид оказался кометой"
    if "west africa" in text and "rainfall" in text:
        return "Изменение климата повысило вероятность экстремальных осадков в Западной Африке"
    if "astronaut" in text and "mitochondria" in text and "space station" in text:
        return "Исследование МКС связало ухудшение состояния организма астронавтов с митохондриями"
    if "reverse federalism" in text and "ai governance" in text:
        return "OpenAI предложила объединять региональные и федеральные правила безопасности ИИ"
    if "anise glide" in text:
        return "Audio Spices выпустила ревербератор Anise Glide со сдвигом высоты тона"
    if "gpt-red" in text:
        return "OpenAI представила GPT-Red для поиска слабых мест моделей"
    if "artemis iii" in text and "lander test" in text:
        return "NASA готовит испытание посадочной системы Artemis III перед высадкой на Луну"
    if "jetson thor" in text:
        return "NVIDIA представила компьютеры Jetson Thor для робототехники"
    if "music plugins" in text and ("week" in text or "weekly" in text):
        return "Новые аудиоплагины недели: платные и бесплатные инструменты"
    if "windup watch fair" in text:
        return "Пять заметных новинок выставки Windup Watch Fair в Чикаго"
    if "second-hand horology" in text or ("used gem" in text and "watch" in text):
        return "Почему находки подержанных часов ценят сильнее обычной покупки"
    if stream_slug(item) == "dj-audio-creative" and original_product and any(
        term in text for term in ("synth", "synthesizer", "midi", "plugin", "pedal", "sampler", "sequencer", "audio interface")
    ):
        return f"Новый аудиоинструмент: {public_text(original_product)}"
    if "fca" in text and "crypto rules" in text:
        return "FCA описала новые правила для криптоактивов"
    if "financial crime" in text:
        return "FCA сообщает о контролях против финансовых преступлений"
    if "consumer duty" in text:
        return "FCA уточняет применение Consumer Duty"
    if "exchange-traded fund" in text or "etf" in text:
        return title_with_original_ru("SEC запрашивает комментарии по биржевым фондам", title)
    if "ofac" in text or "sanctions" in text:
        return "Источник сообщает о санкциях и криптокошельках"
    if "robinhood" in text and "blockchain" in text:
        return "Robinhood развивает публичный блокчейн и криптоторговлю"
    if "ethereum" in text and "policy guide" in text:
        return "Ethereum Foundation описывает сценарии для институтов и государств"
    if "ethereum" in text and "nonprofit" in text:
        return "Вокруг Ethereum появляется новая институциональная организация"
    if "metaplanet" in text or "treasury" in text:
        return "Источник сообщает об увеличении корпоративного биткоин-резерва"
    if "ofac" in text or "sanctions" in text:
        return "Источник сообщает о санкциях и криптокошельках"
    if "bitcoin" in text and ("above" in text or "tops" in text or "holds" in text or "breaks" in text):
        return "Источник сообщает о движении биткоина выше ключевого уровня"
    if "ether" in text or "solana" in text or "dogecoin" in text:
        return title_with_original_ru("Источник сообщает о движении крупных криптоактивов", title)
    if "workspace" in text and "indirect" in text:
        return "Google описывает защиту Workspace от непрямых атак на инструкции"
    if "apple intelligence" in text:
        return "Apple расширяет функции ИИ в пользовательских сценариях"
    if "nvidia" in text and "inference" in text:
        return "NVIDIA объясняет снижение стоимости инференса"
    if "webb" in text and "esa" in text:
        return title_with_original_ru("ESA сообщает о наблюдениях Webb", title)
    if "moon" in text and "nasa" in text:
        return "NASA расширяет научную программу для лунной базы"
    if "ableton" in text or "cubase" in text:
        return "Аудиоинструменты переходят к новым рабочим наборам"
    if is_market_forecast_item(item):
        return f"Источник сообщает об оценке участника рынка: {russian_topic(item)}"
    return fallback_reader_title_ru(item)


def generated_factual_summary_ru(item: dict[str, Any], max_len: int = 360) -> str:
    """Build a conservative Russian summary from attributable source text."""
    text = item_text(item)
    source = public_text(source_name(item))
    topic = russian_topic(item)
    original_title = source_original_title(item)
    original_product = original_title.split(":", 1)[0].strip() if ":" in original_title else ""
    raw_detail = item.get("source_excerpt") or item.get("summary") or original_title
    source_detail = clean_source_excerpt(raw_detail, max_len=280)
    attributed_detail = f"Кратко по сообщению {source}: {public_text(source_detail)}" if source_detail else ""

    if "galaxy" in text and "stablecoin yield" in text and "defi vault" in text:
        summary = (
            "Galaxy представила DeFi-хранилища, ориентированные на институциональные стратегии доходности в стейблкоинах. "
            "Продукт связан с размещением цифровых активов в децентрализованной финансовой инфраструктуре."
        )
    elif "sec vs cftc" in text and "regulates crypto" in text:
        summary = (
            "Надзор за крипторынком в США разделён между SEC и CFTC. "
            "SEC рассматривает активы с признаками инвестиций, а CFTC отвечает за товары, фьючерсы и связанные с ними деривативы."
        )
    elif "citadel securities" in text and "crypto.com" in text and "$400 million" in text:
        summary = (
            "Citadel Securities инвестирует $400 млн в Crypto.com в первом институциональном раунде биржи. "
            "Сделка оценивает площадку в $20 млрд; средства направят на токенизированные бумаги и деривативы."
        )
    elif "federal reserve" in text and "enforcement action" in text and "heritage state bank" in text:
        summary = (
            "Федеральная резервная система сообщила о надзорной мере в отношении бывшего главного кредитного директора Heritage State Bank. "
            "Детали и условия меры следует проверять в документе регулятора."
        )
    elif "7700x3d" in text and "exclusive to newegg" in text and "$329" in text:
        summary = (
            "Процессор AMD Ryzen 7 7700X3D продаётся за $329 эксклюзивно в Newegg в США и Канаде до конца третьего квартала 2026 года. "
            "Источник отмечает сильную игровую производительность, но указывает на более универсальные варианты для рабочих задач."
        )
    elif "fatf" in text and "aml enforcement" in text and "stablecoin crime" in text:
        summary = (
            "FATF призвала страны быстрее применять требования против отмывания денег к криптосервисам. "
            "Организация связывает срочность мер с ростом незаконного использования стейблкоинов."
        )
    elif "bank of canada" in text and "monetary policy report" in text:
        summary = (
            "Банк Канады опубликовал июльский доклад о денежно-кредитной политике. "
            "Регулятор отмечает слабость экономики с признаками улучшения, ожидает ускорения роста и замедления инфляции примерно до 2%, сохраняя высокую неопределённость."
        )
    elif "bank of canada" in text and "maintains the policy rate" in text:
        summary = (
            "Банк Канады сохранил целевую ставку овернайт на уровне 2,25%. "
            "Банковская ставка осталась на уровне 2,5%, ставка по депозитам — 2,2%."
        )
    elif "sec" in text and "e-delivery" in text:
        summary = (
            "SEC предложила изменить порядок электронной доставки документов инвесторам. "
            "Инициатива направлена на более доступное получение обязательной информации; окончательный эффект зависит от обсуждения и статуса правила."
        )
    elif "bank of england" in text and "systemic stablecoin" in text:
        summary = (
            "FCA и Банк Англии представили совместный подход к надзору за системными эмитентами "
            "стейблкоинов. По сообщению регуляторов, документ распределяет обязанности между ведомствами."
        )
    elif "bitcoin wallet" in text and "dormant" in text and "moved" in text:
        amount_match = re.search(r"\$\s?[\d.,]+\s*(?:million|billion)?", text, flags=re.IGNORECASE)
        amount = amount_match.group(0).replace("million", "млн").replace("billion", "млрд") if amount_match else "крупную сумму"
        summary = f"По данным {source}, биткоин-кошелёк, неактивный с 2017 года, переместил активы на {amount}."
        if "fresh address rather than an exchange" in text or "new address rather than an exchange" in text:
            summary += " Средства поступили на новый адрес, а не на биржу; источник не сообщает о продаже."
    elif "fca" in text and "crypto rules" in text:
        summary = (
            "FCA представила новый набор правил для британского рынка криптоактивов. "
            "По сообщению регулятора, изменения затрагивают надзор и требования к участникам рынка."
        )
    elif "illegal promotions" in text and "market abuse" in text:
        summary = (
            "FCA отчиталась об усилении контроля незаконного продвижения криптопродуктов и рыночных злоупотреблений. "
            "Сообщение относится к первому году новой надзорной стратегии."
        )
    elif "ace studio 2" in text and "review" in text:
        summary = (
            "MusicTech протестировал ACE Studio 2 — рабочую станцию с функциями генеративного аудио. "
            "Обзор оценивает возможности ИИ и удобство повседневного творческого процесса."
        )
    elif "rtx 3060" in text and "palit" in text:
        summary = (
            "Palit анонсировала GeForce RTX 3060 Infinity 2 OC с 12 ГБ видеопамяти. "
            "По данным источника, модель возвращает архитектуру поколения 2021 года как более доступный вариант на фоне спроса на ИИ-оборудование."
        )
    elif "west africa" in text and "rainfall" in text:
        summary = (
            "Исследование связывает изменение климата с ростом вероятности экстремальных осадков в Западной Африке. "
            "По сообщению источника, подобные события стали вероятнее примерно в пять раз."
        )
    elif "gpt-red" in text:
        summary = (
            "OpenAI представила GPT-Red — исследовательский подход к самосовершенствованию устойчивости моделей. "
            "Материал описывает работу над поиском слабых мест и повышением надёжности систем ИИ."
        )
    elif "jetson thor" in text:
        summary = (
            "NVIDIA представила компьютеры Jetson Thor для робототехники и периферийных систем ИИ. "
            "Компания позиционирует платформу как основу для более производительных автономных устройств."
        )
    elif "gecko" in text and "cancer" in text:
        summary = (
            "Исследователи изучают особенности домашнего геккона как возможную модель для исследований рака. "
            "Публикация описывает ранний научный результат, который ещё требует дальнейшей проверки."
        )
    elif "music plugins" in text and ("week" in text or "weekly" in text):
        summary = (
            "MusicTech собрал новые платные и бесплатные аудиоплагины недели. "
            "Подборка помогает сравнить свежие инструменты для производства и обработки звука."
        )
    elif "fender" in text and "studio pro" in text and "ableton" in text:
        summary = (
            "MusicTech сравнил Fender Studio Pro 8.1 с Ableton Live в реальном рабочем сценарии. "
            "Обзор оценивает удобство перехода, возможности станции и ограничения нового процесса."
        )
    elif "china" in text and "chip exports" in text:
        summary = (
            "По данным источника, стоимость экспорта китайских чипов заметно выросла в первой половине года. "
            "На показатель повлияли рост цен на память и увеличение стоимости поставок."
        )
    elif "windup watch fair" in text:
        summary = (
            "Worn & Wound выбрал пять заметных новых моделей с выставки Windup Watch Fair в Чикаго. "
            "Материал представляет редакционный обзор дизайна и практических особенностей часов."
        )
    elif "second-hand horology" in text or ("used gem" in text and "watch" in text):
        summary = (
            "Worn & Wound рассказывает о поиске подержанных часов в локальных магазинах, на барахолках и распродажах. "
            "Материал рассматривает ценность случайной находки, состояние вещи и личную историю коллекционирования."
        )
    elif stream_slug(item) == "dj-audio-creative" and original_product and any(
        term in text for term in ("synth", "synthesizer", "midi", "plugin", "pedal", "sampler", "sequencer", "audio interface")
    ):
        summary = (
            f"По сообщению {source}, представлен аудиоинструмент {public_text(original_product)}. "
            "Материал описывает его функции, совместимость и сценарии использования в музыкальном производстве."
        )
    elif "astronaut" in text and "mitochondria" in text and "space station" in text:
        summary = (
            "Исследование на Международной космической станции указывает на роль митохондрий в ухудшении состояния организма астронавтов. "
            "Nature описывает научный результат, который требует оценки методики и дальнейшего подтверждения."
        )
    elif "perseverance" in text and "ancient mars impacts" in text:
        summary = (
            "Марсоход Perseverance обнаружил у кратера Езеро слой древних пород толщиной около 75 метров. "
            "NASA связывает его формирование с повторными астероидными ударами более 3,9 млрд лет назад."
        )
    elif "perseverance" in text and "broom point" in text:
        summary = (
            "NASA показала маршрут марсохода Perseverance к участку Broom Point у кратера Езеро. "
            "Там находится последовательность слоистых пород, возраст которых может превышать 3,9 млрд лет."
        )
    elif "young galaxy cluster" in text and ("webb" in text or "james webb" in text):
        summary = (
            "Телескоп James Webb показал скопление MACS J0553.4-3342 таким, каким оно было 4,4 млрд лет назад. "
            "По данным NASA, оно состоит из двух активно сливающихся субскоплений сопоставимой массы."
        )
    elif "digital euro" in text and "cooperative spirit" in text:
        summary = (
            "Член правления ЕЦБ Пьеро Чиполлоне выступил о цифровом евро и роли сотрудничества банков в его развитии. "
            "Материал передаёт позицию ЕЦБ; конкретные условия проекта следует сверять с документами регулятора."
        )
    elif "teens deserve access to safe ai" in text:
        summary = (
            "OpenAI описала меры для более безопасного использования ChatGPT подростками. "
            "Компания называет возрастные ограничения, учебные инструменты, родительский контроль и работу с профильными экспертами."
        )
    elif "eu will force google" in text and "search data" in text and "android" in text:
        summary = (
            "По данным Ars Technica, ЕС потребует от Google делиться поисковыми данными и открыть доступ к функциям ИИ на Android. "
            "Google предупреждает, что изменения могут повлиять на приватность и безопасность пользователей."
        )
    elif "nanopore" in text and "current-induced heating" in text and "memory operations" in text:
        summary = (
            "Исследователи представили жидкостное нанопоровое устройство для нейроморфных вычислений. "
            "Опубликованная в Nature Communications работа использует нагрев электрическим током для операций памяти."
        )
    elif "nodus" in text and "raven" in text and "trailtrekker" in text:
        summary = (
            "Nodus и Raven выпустили четвёртую версию часов TrailTrekker. "
            "Спортивная GMT-модель получила выраженный EDC-дизайн и детали из кованого углеволокна на циферблате и безеле."
        )
    elif "balyasny" in text and "ai research engine" in text:
        summary = (
            "Balyasny Asset Management создала систему для инвестиционных исследований на основе ИИ. "
            "По сообщению OpenAI, в ней объединены оценка моделей, инструменты платформы и агентные рабочие процессы."
        )
    elif "near-earth asteroid" in text and "actually comet" in text:
        summary = (
            "Исследователи NASA определили, что загадочный околоземный объект является кометой, а не астероидом. "
            "Вывод сделан по точному отслеживанию движения и данным обсерваторий, способных видеть слабые небесные объекты."
        )
    elif "reverse federalism" in text and "ai governance" in text:
        summary = (
            "OpenAI описала подход «обратного федерализма» к регулированию ИИ в США. "
            "Предложение предполагает использовать законы штатов как основу общенациональной системы безопасного и демократического ИИ."
        )
    elif "anise glide" in text:
        summary = (
            "Audio Spices выпустила Anise Glide — ревербератор со сдвигом высоты тона. "
            "Плагин плавно переходит к выбранной ноте и создаёт изменяющееся движение звука."
        )
    elif "artemis iii" in text and "lander test" in text:
        summary = (
            "NASA планирует демонстрационную миссию Artemis III на 2027 год перед высадкой астронавтов в 2028 году. "
            "Испытание должно отработать сближение и стыковку посадочной системы с кораблём Orion."
        )
    elif "review" in text:
        summary = attributed_detail or (
            f"{source} опубликовал практический обзор по теме «{topic}». "
            "Материал оценивает заявленные возможности, ограничения и сценарии использования."
        )
    elif any(term in text for term in ("study finds", "researchers found", "study shows", "research shows")):
        summary = attributed_detail or (
            f"По сообщению {source}, опубликован новый исследовательский результат по теме «{topic}». "
            "Выводы основаны на данных авторов и требуют оценки методики и независимого подтверждения."
        )
    elif any(term in text for term in ("launches", "launched", "introduces", "introduced", "announces", "announced", "unveils")):
        summary = attributed_detail or (
            f"По сообщению {source}, представлен новый продукт или обновление по теме «{topic}». "
            "Источник описывает заявленные возможности; фактическая доступность и ограничения требуют проверки."
        )
    elif any(term in text for term in ("rules", "regulation", "regulatory", "supervision", "enforcement")):
        summary = attributed_detail or (
            f"По сообщению {source}, опубликовано изменение правил или надзорного подхода по теме «{topic}». "
            "Практический эффект зависит от статуса документа, сроков и круга затронутых участников."
        )
    else:
        summary = attributed_detail or (
            f"По сообщению {source}, опубликованы новые сведения по теме «{topic}». "
            "Материал передаёт позицию источника; ключевые детали и последствия требуют сверки с первоисточником."
        )
    return clean_source_excerpt(summary, max_len=max_len)


def reader_excerpt_ru(item: dict[str, Any], max_len: int = 360) -> str:
    existing = str(item.get("reader_excerpt_ru") or "").strip()
    if existing:
        cleaned = clean_source_excerpt(public_text(existing), max_len=max_len)
        if has_cyrillic(cleaned) and not is_generic_reader_summary(cleaned) and not any(
            phrase in cleaned
            for phrase in (
                "Источник описывает тему",
                "Подробности и формулировки сохранены",
                "Короткое сообщение источника",
            )
        ):
            return cleaned
    excerpt = clean_source_excerpt(item.get("source_excerpt") or item.get("summary") or "", max_len=max_len)
    if excerpt and has_cyrillic(excerpt):
        return public_text(excerpt)
    if is_market_forecast_item(item):
        text = f"Источник сообщает об оценке участника рынка по теме «{russian_topic(item)}». Это не факт будущей цены и не рекомендация."
    else:
        text = generated_factual_summary_ru(item, max_len=max_len)
    return clean_source_excerpt(text, max_len=max_len)


def reader_source_line_ru(item: dict[str, Any]) -> str:
    existing = str(item.get("reader_source_line_ru") or "").strip()
    if existing:
        return public_text(existing)
    source = public_text(source_name(item))
    stream = stream_label(stream_slug(item))
    reliability = source_class_label(item.get("source_class"))
    time = compact_time_ru(item.get("published") or item.get("date"))
    return f"{source} · {stream} · {time} · {reliability}"


def source_original_title(item: dict[str, Any]) -> str:
    return str(item.get("source_original_title") or item.get("title") or "").strip()


def source_original_url(item: dict[str, Any]) -> str:
    return str(item.get("source_original_url") or item.get("url") or "").strip()


def build_reader_fields(item: dict[str, Any]) -> dict[str, str]:
    return {
        "reader_title_ru": reader_title_ru(item),
        "reader_excerpt_ru": reader_excerpt_ru(item),
        "reader_source_line_ru": reader_source_line_ru(item),
    }


def public_source_name(item: dict[str, Any]) -> str:
    source = str(item.get("feed_title") or "").strip()
    if not source:
        return "Публичный источник"
    return public_text(source)


def public_stream_name(item: dict[str, Any], stream: object | None = None) -> str:
    return stream_label(stream if stream is not None else stream_slug(item))


def public_reliability_label(item: dict[str, Any]) -> str:
    source_class = str(item.get("source_class") or "").strip()
    source_type = str(item.get("source_type") or "").strip()
    return source_class_label(source_class) if source_class else source_type_label(source_type)


def public_topic_sentence(item: dict[str, Any]) -> str:
    source = public_source_name(item)
    topic = russian_topic(item)
    if source == "Google Security Blog" and topic == "безопасность и технологическая инфраструктура":
        return "Google описывает безопасность и технологическую инфраструктуру"
    if source == "Google Security Blog":
        return f"Google описывает тему «{topic}»"
    return f"{source} описывает тему «{topic}»"


def public_title_ru(item: dict[str, Any]) -> str:
    if is_market_forecast_item(item):
        return f"Источник сообщает об оценке участника рынка: {russian_topic(item)}"
    title = public_text(reader_title_ru(item)).strip()
    if re.search(r"Источник сообщает:\s*.+\s+—\s+", title) or title.startswith(("Источник сообщает: ", "Источник описывает ")):
        return fallback_reader_title_ru(item)
    source = public_source_name(item)
    generic_source_topic = f"{source}: {russian_topic(item)}"
    if is_source_topic_title(title):
        return public_topic_sentence(item)
    if title == generic_source_topic:
        return public_topic_sentence(item)
    if title and has_cyrillic(title):
        return title
    return fallback_reader_title_ru(item)


def public_story_key(item: dict[str, Any], stream: object | None = None) -> str:
    """Return a stable reader-facing identity used to suppress visible repeats."""
    del stream
    title = source_original_title(item) or public_title_ru(item)
    title = title.lower()
    normalized = re.sub(r"[^0-9a-zа-яё]+", " ", title).strip()
    return normalized or str(item.get("url") or item.get("item_key") or "").strip().lower()


def public_story_terms(item: dict[str, Any]) -> set[str]:
    """Return distinctive title terms for conservative cross-source clustering."""
    titles = [source_original_title(item), str(item.get("reader_title_ru") or "").strip()]
    text = " ".join(title for title in titles if title).lower().replace("ё", "е")
    terms = set(re.findall(r"[0-9a-zа-я]{2,}", text))
    return {
        term
        for term in terms
        if term not in PUBLIC_STORY_STOPWORDS and len(term) >= 3
    }


def public_story_similarity(left: dict[str, Any], right: dict[str, Any]) -> float:
    if stream_slug(left) != stream_slug(right):
        return 0.0
    left_terms = public_story_terms(left)
    right_terms = public_story_terms(right)
    if not left_terms or not right_terms:
        return 0.0
    overlap = len(left_terms & right_terms)
    if overlap < 2:
        return 0.0
    return overlap / min(len(left_terms), len(right_terms))


def public_items_same_story(left: dict[str, Any], right: dict[str, Any], threshold: float = 0.62) -> bool:
    """Identify one public story without merging merely related publisher updates."""
    left_url = str(left.get("url") or left.get("source_original_url") or "").strip().lower()
    right_url = str(right.get("url") or right.get("source_original_url") or "").strip().lower()
    if left_url and left_url == right_url:
        return True
    left_key = public_story_key(left)
    right_key = public_story_key(right)
    if left_key and left_key == right_key:
        return True
    if stream_slug(left) != stream_slug(right):
        return False
    left_public_title = normalized_public_topic(public_title_ru(left))
    right_public_title = normalized_public_topic(public_title_ru(right))
    if left_public_title and left_public_title == right_public_title:
        return True
    left_source = str(left.get("publisher_id") or left.get("feed_id") or left.get("feed_title") or "").strip().lower()
    right_source = str(right.get("publisher_id") or right.get("feed_id") or right.get("feed_title") or "").strip().lower()
    if left_source and left_source == right_source:
        return False
    return public_story_similarity(left, right) >= threshold


def public_why_it_matters_ru(item: dict[str, Any], stream: object | None = None, max_len: int = 280) -> str:
    existing = str(item.get("why_it_matters") or item.get("reader_why_it_matters_ru") or "").strip()
    if existing:
        return clean_source_excerpt(public_text(existing), max_len=max_len)
    text = item_text(item)
    if "stablecoin" in text or "crypto rules" in text or "regulation" in text:
        value = "Изменения могут затронуть эмитентов, банки, биржи, кастодианов и платёжные сервисы; важны сроки и точный статус правил."
    elif any(term in text for term in ("gpu", "chip", "jetson", "hardware", "rtx")):
        value = "Изменение может повлиять на доступность оборудования, цены, совместимость и выбор технологической платформы."
    elif any(term in text for term in ("study", "research", "scientists", "researchers")):
        value = "Результат расширяет научную картину, но практические выводы зависят от методики, повторяемости и независимого подтверждения."
    elif any(term in text for term in ("model", "gpt", "agent", "artificial intelligence", " ai ")):
        value = "Новость может повлиять на доступность инструментов ИИ, требования к инфраструктуре и условия интеграции в продукты."
    else:
        slug = str(stream or stream_slug(item)).strip()
        value = WHY_IT_MATTERS_BY_STREAM.get(slug, "")
    return clean_source_excerpt(value, max_len=max_len)


def public_excerpt_ru(item: dict[str, Any], max_len: int = 240) -> str:
    forbidden = (
        "Источник описывает тему",
        "Подробности и формулировки сохранены",
        "Короткое сообщение источника",
        "Источник сообщает: ",
    )
    if is_market_forecast_item(item):
        return clean_source_excerpt(
            f"Источник сообщает об оценке участника рынка по теме «{russian_topic(item)}». Это не факт будущей цены и не рекомендация.",
            max_len=max_len,
        )
    existing = str(item.get("reader_excerpt_ru") or "").strip()
    if existing:
        text = public_text(reader_excerpt_ru(item, max_len=max_len))
        if has_cyrillic(text) and not is_generic_reader_summary(text) and not any(phrase in text for phrase in forbidden):
            return text
    excerpt = clean_source_excerpt(item.get("source_excerpt") or item.get("summary") or "", max_len=max_len)
    if excerpt and has_cyrillic(excerpt):
        text = public_text(excerpt)
        return "" if any(phrase in text for phrase in forbidden) else text
    return generated_factual_summary_ru(item, max_len=max_len)


def public_meta_ru(item: dict[str, Any], stream: object | None = None) -> str:
    parts = [
        public_source_name(item),
        public_stream_name(item, stream),
        format_public_time_ru(item.get("published") or item.get("date")),
        public_reliability_label(item),
    ]
    return " · ".join(part for part in parts if part)


def build_public_item(item: dict[str, Any], stream: object | None = None) -> dict[str, str]:
    original = public_text(source_original_title(item)).strip()
    title = public_title_ru(item)
    excerpt = public_excerpt_ru(item)
    return {
        "title": title,
        "excerpt": excerpt,
        "summary": excerpt,
        "why_it_matters": public_why_it_matters_ru(item, stream),
        "meta": public_meta_ru(item, stream),
        "time": format_public_time_ru(item.get("published") or item.get("date")),
        "published_at": str(item.get("published") or item.get("date") or "").strip(),
        "story_key": public_story_key(item, stream),
        "source": public_source_name(item),
        "stream": public_stream_name(item, stream),
        "reliability": public_reliability_label(item),
        "url": str(item.get("url") or "").strip(),
        "original_title": original if original != title else "",
    }
