#!/usr/bin/env python3
"""Reader-facing text helpers for public News Dispatch pages."""

from __future__ import annotations

import re
from datetime import datetime, time
from typing import Any
from zoneinfo import ZoneInfo

from core import clean_text

STREAM_LABELS = {
    "finance": "Финансы",
    "crypto-finance": "Криптофинансы",
    "ai": "ИИ",
    "tech-hardware-software": "Железо и софт",
    "gear-style-edc": "EDC / стиль / вещи",
    "moscow-city": "Москва",
    "dj-audio-creative": "DJ / аудио / креатив",
    "science-discovery": "Наука",
    "general": "Спецвыпуски",
}

PUBLIC_TZ = ZoneInfo("Europe/Moscow")
MONTHS_RU = {
    1: "января",
    2: "февраля",
    3: "марта",
    4: "апреля",
    5: "мая",
    6: "июня",
    7: "июля",
    8: "августа",
    9: "сентября",
    10: "октября",
    11: "ноября",
    12: "декабря",
}

SOURCE_CLASS_LABELS = {
    "official": "официальный источник",
    "official_source": "официальный источник",
    "regulator": "регулятор",
    "company": "компания",
    "public_media": "публичное медиа",
    "business_media": "деловое медиа",
    "industry_media": "отраслевой источник",
    "specialized_media": "отраслевой источник",
    "research_media": "исследовательский источник",
}

SOURCE_TYPE_REPLACEMENTS = {
    "official": "официальный источник",
    "official source": "официальный источник",
    "official_source": "официальный источник",
    "public source": "публичный источник",
    "public_source": "публичный источник",
    "media": "медиа",
    "security": "безопасность",
    "research": "исследования",
    "preprint": "предварительное исследование",
    "ai lab": "лаборатория ИИ",
}

PUBLIC_TEXT_REPLACEMENTS = [
    (r"AI-generated", "созданный ИИ"),
    (r"generated by AI", "созданный ИИ"),
    (r"\bgenerated\b", "созданный"),
    (r"\bprompt\b", "инструкция"),
    (r"\bmodel\b", "модель"),
    (r"\bcredentials?\b", "учётные данные"),
    (r"\bcookies?\b", "cookie-файлы"),
    (r"\btokens?\b", "токены"),
    (r"\bsessions?\b", "сессии"),
    (r"\bJSON\b", "данные"),
    (r"\bselected\b", "отобранный"),
    (r"\breader_safe\b", "публичный"),
    (r"\bsource_rule_status\b", "статус источника"),
    (r"\bvalidation\b", "проверка"),
    (r"\bdraft-only\b", "подготовительный"),
    (r"\breview-only\b", "требующий проверки"),
    (r"\bscore\b", "оценка"),
]

BOILERPLATE_PATTERNS = [
    r"read more\s*",
    r"continue reading\s*",
    r"the post .* appeared first on .*",
    r"click here to read .*",
    r"подробнее\s*",
    r"читать далее\s*",
]

GENERIC_SOURCE_TOPICS = {
    "регуляторика и надзор",
    "банки ставки и ликвидность",
    "безопасность и технологическая инфраструктура",
    "модели и инфраструктура ии",
    "движение крипторынка",
}


def has_cyrillic(text: object) -> bool:
    return bool(re.search(r"[А-Яа-яЁё]", str(text or "")))


def public_text(value: object) -> str:
    text = str(value or "")
    for pattern, replacement in PUBLIC_TEXT_REPLACEMENTS:
        text = re.sub(pattern, replacement, text, flags=re.IGNORECASE)
    return text


def normalized_public_topic(text: object) -> str:
    raw = re.sub(r"\s+", " ", str(text or "")).strip().lower()
    return re.sub(r"[^0-9a-zа-яё]+", " ", raw).strip()


def has_market_regulator_token(text: str, token: str | None = None) -> bool:
    pattern = r"\b(sec|fca|esma|cftc)\b" if token is None else rf"\b{re.escape(token)}\b"
    return bool(re.search(pattern, text, flags=re.IGNORECASE))


def is_source_topic_title(title: object) -> bool:
    text = str(title or "")
    if ":" not in text:
        return False
    _source, topic = text.split(":", 1)
    return normalized_public_topic(topic) in GENERIC_SOURCE_TOPICS


def stream_slug(item: dict[str, Any]) -> str:
    return str(item.get("routed_stream") or item.get("configured_stream") or "").strip()


def stream_label(slug: object) -> str:
    text = str(slug or "")
    return STREAM_LABELS.get(text, text or "Без потока")


def source_name(item: dict[str, Any]) -> str:
    return str(item.get("feed_title") or item.get("feed_id") or "Публичный источник")


def source_class_label(value: object) -> str:
    text = str(value or "").strip()
    return SOURCE_CLASS_LABELS.get(text, text.replace("_", " ") if text else "публичный источник")


def source_type_label(value: object) -> str:
    text = str(value or "").strip()
    if not text:
        return "публичный источник"
    lowered = text.lower().replace("/", " / ")
    for source, target in SOURCE_TYPE_REPLACEMENTS.items():
        lowered = lowered.replace(source, target)
    return " ".join(lowered.split())


def compact_time_ru(value: object) -> str:
    raw = str(value or "").strip()
    if not raw:
        return "время не указано"
    try:
        parsed = datetime.fromisoformat(raw.replace("Z", "+00:00"))
        local = parsed.astimezone(ZoneInfo("Europe/Moscow"))
        return local.strftime("%H:%M")
    except (ValueError, TypeError):
        cleaned = raw.replace("T", " ").split(".", 1)[0].replace("+00:00", "")
        return cleaned[:16] if cleaned else "время не указано"


def parse_public_datetime(value: object) -> tuple[datetime | None, bool]:
    raw = str(value or "").strip()
    if not raw:
        return None, False
    has_time = bool(re.search(r"[T ]\d{1,2}:\d{2}", raw))
    cleaned = raw.replace("Z", "+00:00")
    try:
        parsed = datetime.fromisoformat(cleaned)
    except ValueError:
        date_match = re.match(r"^(\d{4})-(\d{2})-(\d{2})$", raw)
        if not date_match:
            return None, False
        year, month, day = (int(part) for part in date_match.groups())
        return datetime(year, month, day, tzinfo=PUBLIC_TZ), False
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=PUBLIC_TZ)
    else:
        parsed = parsed.astimezone(PUBLIC_TZ)
    return parsed, has_time


def format_public_time_ru(value: object) -> str:
    parsed, has_time = parse_public_datetime(value)
    if parsed is None:
        return "дата не указана"
    day = f"{parsed.day} {MONTHS_RU[parsed.month]}"
    if has_time and parsed.date() == datetime.now(PUBLIC_TZ).date():
        return f"Сегодня, {parsed:%H:%M}"
    if has_time and parsed.timetz().replace(tzinfo=None) != time(0, 0):
        return f"{day}, {parsed:%H:%M}"
    return day


def clean_source_excerpt(value: object, max_len: int = 360) -> str:
    text = clean_text(value, max_len=max_len)
    for pattern in BOILERPLATE_PATTERNS:
        text = re.sub(pattern, " ", text, flags=re.IGNORECASE)
    return clean_text(text, max_len=max_len)


def item_text(item: dict[str, Any]) -> str:
    parts = [
        str(item.get("title") or ""),
        str(item.get("source_original_title") or ""),
        str(item.get("source_excerpt") or ""),
        str(item.get("feed_title") or ""),
        str(item.get("feed_id") or ""),
    ]
    for key in ("include_hits", "boost_hits", "stream_keyword_hits"):
        value = item.get(key)
        if isinstance(value, list):
            parts.extend(str(part) for part in value)
    return " ".join(parts).lower()


def is_market_forecast_item(item: dict[str, Any]) -> bool:
    if stream_slug(item) not in {"finance", "crypto-finance"}:
        return False
    if str(item.get("market_signal_type") or "") == "third_party_forecast":
        return True
    return bool(re.search(r"\b(price targets?|forecast|predict|estimate|outlook|analyst|strategist|12[-\s]?month|year[-\s]?end|slashes|raises)\b", item_text(item), re.I))


def russian_topic(item: dict[str, Any]) -> str:
    text = item_text(item)
    stream = stream_slug(item)
    if "mica" in text:
        return "европейские правила MiCA"
    if "dora" in text and "ict" in text:
        return "инциденты DORA в цифровой инфраструктуре"
    if "bank of england" in text and "stablecoin" in text:
        return "подход к системным стейблкоинам"
    if "crédit agricole" in text or "credit agricole" in text:
        return "евро-стейблкоин Crédit Agricole"
    if "taiwan" in text and "regulation" in text:
        return "правила Тайваня для криптоактивов"
    if "federal reserve" in text and "stablecoin" in text:
        return "идентификация клиентов эмитентов стейблкоинов"
    if "stablecoin" in text or "стейбл" in text:
        return "стейблкоины и платёжная инфраструктура"
    if has_market_regulator_token(text, "sec") and "market statistics" in text:
        return "статистика рынка SEC"
    if "central bank" in text and "digital asset" in text:
        return "правила центрального банка для цифровых активов"
    if has_market_regulator_token(text):
        return "регуляторика и надзор"
    if "post-quantum" in text or ("quantum" in text and "android" in text):
        return "постквантовая защита Android"
    if "crypto rules" in text or "crypto rulebook" in text:
        return "правила для криптоактивов"
    if "financial crime" in text:
        return "контроль финансовых преступлений"
    if "consumer duty" in text:
        return "применение Consumer Duty"
    if "exchange-traded fund" in text or "etf" in text:
        return "биржевые фонды и рыночная инфраструктура"
    if "ofac" in text or "sanctions" in text:
        return "санкции и криптокошельки"
    if "robinhood" in text and "blockchain" in text:
        return "блокчейн-планы Robinhood"
    if "ethereum" in text:
        return "институциональная инфраструктура Ethereum"
    if "metaplanet" in text or "treasury" in text:
        return "биткоин-резервы компаний"
    if "bitcoin" in text or "ether" in text or "solana" in text or "dogecoin" in text:
        return "движение крипторынка"
    if "security" in text or "cryptography" in text or "supply chain" in text:
        return "безопасность и технологическая инфраструктура"
    if "apple intelligence" in text:
        return "функции ИИ в пользовательских сценариях"
    if "openai" in text or "anthropic" in text or "deepmind" in text or "model" in text:
        return "модели и инфраструктура ИИ"
    if "central bank" in text or "ставк" in text or "цб" in text:
        return "банки, ставки и ликвидность"
    if "webb" in text or "nasa" in text or "esa" in text or "moon" in text:
        return "космические и научные наблюдения"
    if "ableton" in text or "cubase" in text or "plugin" in text or "controller" in text:
        return "аудиоинструменты и творческие рабочие процессы"
    if "watch" in text or "carry" in text or "material" in text or "design" in text:
        return "дизайн, материалы и практическое использование"
    if stream == "moscow-city":
        return "городская инфраструктура и сервисы"
    return stream_label(stream).lower()


def reader_title_ru(item: dict[str, Any]) -> str:
    existing = str(item.get("reader_title_ru") or "").strip()
    if existing:
        return public_text(existing)
    title = str(item.get("source_original_title") or item.get("title") or "").strip()
    if has_cyrillic(title):
        return public_text(title)
    text = item_text(item)
    source = source_name(item)
    if "bank of england" in text and "stablecoin" in text:
        return "FCA и Банк Англии описали подход к системным стейблкоинам"
    if "mica" in text:
        return "Европейские правила MiCA снова в фокусе регуляторов"
    if "dora" in text and "ict" in text:
        return "Европейские надзорные органы публикуют отчёт об ICT-инцидентах DORA"
    if has_market_regulator_token(text, "sec") and "market statistics" in text:
        return "SEC обновила статистику рынка"
    if "crédit agricole" in text or "credit agricole" in text:
        return "Crédit Agricole запускает евро-стейблкоин EURXT"
    if "taiwan" in text and "regulation" in text:
        return "Тайвань продвигает правила для криптоактивов и стейблкоинов"
    if "federal reserve" in text and "stablecoin" in text:
        return "ФРС запрашивает комментарии по идентификации клиентов эмитентов стейблкоинов"
    if "central bank" in text and "digital asset" in text:
        return "Центральный банк обновил правила для цифровых активов"
    if "post-quantum" in text or ("quantum" in text and "android" in text):
        return "Google описывает постквантовую защиту Android"
    if "fca" in text and "crypto rules" in text:
        return "FCA описала новые правила для криптоактивов"
    if "financial crime" in text:
        return "FCA сообщает о контролях против финансовых преступлений"
    if "consumer duty" in text:
        return "FCA уточняет применение Consumer Duty"
    if "exchange-traded fund" in text or "etf" in text:
        return "SEC запрашивает комментарии по биржевым фондам"
    if "ofac" in text or "sanctions" in text:
        return "Источник сообщает о санкциях и криптокошельках"
    if "robinhood" in text and "blockchain" in text:
        return "Robinhood развивает публичный блокчейн и криптоторговлю"
    if "ethereum" in text and "policy guide" in text:
        return "Ethereum Foundation описывает сценарии для институтов и государств"
    if "ethereum" in text and "nonprofit" in text:
        return "Вокруг Ethereum появляется новая институциональная организация"
    if "metaplanet" in text or "treasury" in text:
        return "Источник сообщает об увеличении корпоративного биткоин-резерва"
    if "ofac" in text or "sanctions" in text:
        return "Источник сообщает о санкциях и криптокошельках"
    if "bitcoin" in text and ("above" in text or "tops" in text or "holds" in text or "breaks" in text):
        return "Источник сообщает о движении биткоина выше ключевого уровня"
    if "ether" in text or "solana" in text or "dogecoin" in text:
        return "Источник сообщает о движении крупных криптоактивов"
    if "workspace" in text and "indirect" in text:
        return "Google описывает защиту Workspace от непрямых атак на инструкции"
    if "apple intelligence" in text:
        return "Apple расширяет функции ИИ в пользовательских сценариях"
    if "nvidia" in text and "inference" in text:
        return "NVIDIA объясняет снижение стоимости инференса"
    if "webb" in text and "esa" in text:
        return "ESA сообщает о наблюдениях Webb"
    if "moon" in text and "nasa" in text:
        return "NASA расширяет научную программу для лунной базы"
    if "ableton" in text or "cubase" in text:
        return "Аудиоинструменты переходят к новым рабочим наборам"
    if is_market_forecast_item(item):
        return f"Источник сообщает об оценке участника рынка: {russian_topic(item)}"
    return f"{public_text(source)}: {russian_topic(item)}"


def reader_excerpt_ru(item: dict[str, Any], max_len: int = 360) -> str:
    existing = str(item.get("reader_excerpt_ru") or "").strip()
    if existing:
        return clean_source_excerpt(public_text(existing), max_len=max_len)
    excerpt = clean_source_excerpt(item.get("source_excerpt") or item.get("summary") or "", max_len=max_len)
    if excerpt and has_cyrillic(excerpt):
        return public_text(excerpt)
    title = reader_title_ru(item)
    if is_market_forecast_item(item):
        text = f"Источник сообщает об оценке участника рынка по теме «{russian_topic(item)}». Это не факт будущей цены и не рекомендация."
    elif excerpt:
        text = f"Источник описывает тему «{title}». Подробности и формулировки сохранены в оригинале источника."
    else:
        text = f"Короткое сообщение источника по теме «{title}». Для выводов нужно открыть первичный материал и проверить контекст."
    return clean_source_excerpt(text, max_len=max_len)


def reader_source_line_ru(item: dict[str, Any]) -> str:
    existing = str(item.get("reader_source_line_ru") or "").strip()
    if existing:
        return public_text(existing)
    source = public_text(source_name(item))
    stream = stream_label(stream_slug(item))
    reliability = source_class_label(item.get("source_class"))
    time = compact_time_ru(item.get("published") or item.get("date"))
    return f"{source} · {stream} · {time} · {reliability}"


def source_original_title(item: dict[str, Any]) -> str:
    return str(item.get("source_original_title") or item.get("title") or "").strip()


def source_original_url(item: dict[str, Any]) -> str:
    return str(item.get("source_original_url") or item.get("url") or "").strip()


def build_reader_fields(item: dict[str, Any]) -> dict[str, str]:
    return {
        "reader_title_ru": reader_title_ru(item),
        "reader_excerpt_ru": reader_excerpt_ru(item),
        "reader_source_line_ru": reader_source_line_ru(item),
    }


def public_source_name(item: dict[str, Any]) -> str:
    source = str(item.get("feed_title") or "").strip()
    if not source:
        return "Публичный источник"
    return public_text(source)


def public_stream_name(item: dict[str, Any], stream: object | None = None) -> str:
    return stream_label(stream if stream is not None else stream_slug(item))


def public_reliability_label(item: dict[str, Any]) -> str:
    source_class = str(item.get("source_class") or "").strip()
    source_type = str(item.get("source_type") or "").strip()
    return source_class_label(source_class) if source_class else source_type_label(source_type)


def public_topic_sentence(item: dict[str, Any]) -> str:
    source = public_source_name(item)
    topic = russian_topic(item)
    if source == "Google Security Blog" and topic == "безопасность и технологическая инфраструктура":
        return "Google описывает безопасность и технологическую инфраструктуру"
    if source == "Google Security Blog":
        return f"Google описывает тему «{topic}»"
    return f"{source} описывает тему «{topic}»"


def public_title_ru(item: dict[str, Any]) -> str:
    if is_market_forecast_item(item):
        return f"Источник сообщает об оценке участника рынка: {russian_topic(item)}"
    title = public_text(reader_title_ru(item)).strip()
    original = public_text(source_original_title(item)).strip()
    if re.search(r"Источник сообщает:\s*.+\s+—\s+", title) or title.startswith(("Источник сообщает: ", "Источник описывает ")):
        source = public_source_name(item)
        if original:
            return f"{source}: {original}"
    source = public_source_name(item)
    generic_source_topic = f"{source}: {russian_topic(item)}"
    if is_source_topic_title(title):
        if original and original != title and not is_source_topic_title(original):
            return f"{source}: {original}"
        return public_topic_sentence(item)
    if title == generic_source_topic and original and original != title:
        return f"{source}: {original}"
    return title or "Без заголовка"


def public_story_key(item: dict[str, Any], stream: object | None = None) -> str:
    """Return a stable reader-facing identity used to suppress visible repeats."""
    del stream
    title = public_title_ru(item).lower()
    normalized = re.sub(r"[^0-9a-zа-яё]+", " ", title).strip()
    return normalized or str(item.get("url") or item.get("item_key") or "").strip().lower()


def public_excerpt_ru(item: dict[str, Any], max_len: int = 240) -> str:
    forbidden = (
        "Источник описывает тему",
        "Подробности и формулировки сохранены",
        "Короткое сообщение источника",
        "Источник сообщает: ",
    )
    if is_market_forecast_item(item):
        return clean_source_excerpt(
            f"Источник сообщает об оценке участника рынка по теме «{russian_topic(item)}». Это не факт будущей цены и не рекомендация.",
            max_len=max_len,
        )
    existing = str(item.get("reader_excerpt_ru") or "").strip()
    if existing:
        text = public_text(reader_excerpt_ru(item, max_len=max_len))
        return "" if any(phrase in text for phrase in forbidden) else text
    excerpt = clean_source_excerpt(item.get("source_excerpt") or item.get("summary") or "", max_len=max_len)
    if excerpt:
        text = public_text(excerpt)
        return "" if any(phrase in text for phrase in forbidden) else text
    return ""


def public_meta_ru(item: dict[str, Any], stream: object | None = None) -> str:
    parts = [
        public_source_name(item),
        public_stream_name(item, stream),
        format_public_time_ru(item.get("published") or item.get("date")),
        public_reliability_label(item),
    ]
    return " · ".join(part for part in parts if part)


def build_public_item(item: dict[str, Any], stream: object | None = None) -> dict[str, str]:
    original = public_text(source_original_title(item)).strip()
    title = public_title_ru(item)
    return {
        "title": title,
        "excerpt": public_excerpt_ru(item),
        "meta": public_meta_ru(item, stream),
        "time": format_public_time_ru(item.get("published") or item.get("date")),
        "source": public_source_name(item),
        "stream": public_stream_name(item, stream),
        "reliability": public_reliability_label(item),
        "url": str(item.get("url") or "").strip(),
        "original_title": original if original != title else "",
    }
